# Generated by Django 5.1.3 on 2024-12-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
